[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# React Router / SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache forte para assets com hash
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cabeçalhos de segurança básicos (opcional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    # Content-Security-Policy pode ser ajustado depois se quiser endurecer
